# Generated by Django 3.0.8 on 2020-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200919_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdetails',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
